### ISSUE TITLE
Margins only exist on bottom and left

### ISSUE THREAD

**Issue by John-Colvin** [BlackEdder/plotd#2]
This means that the output is truncated on the top and right edges.

Or maybe I'm just using the settings wrong? The examples in the wiki appear to suffer from the same problem though.

**Comment by BlackEdder** [comment]
Is your issue that the points/lines on the edge are cut off? Or other issues as well? Would the problem be solved by making the plotting area slightly bigger, to enclose the lines/points fully?

**Comment by John-Colvin** [comment]
I would ideally want to have a default that guarantees nothing will be cut off, but manual control over the individual borders would also be useful.

**Comment by BlackEdder** [comment]
Switching to ggplotd introduces margins on all sides. Points can still be cut off, but should be less of a problem.
